### ISSUE TITLE
Create list todo

### ISSUE THREAD

**Issue by Demonbruster** [Demonbruster/todo-app#3]
Create a component to show the list of tasks,

**Comment by thisisfaaris** [comment]
- [ ] Create a component to display the list of tasks.
- [ ] Fetch data from the server to display existing tasks.
- [ ] Update state dynamically when a new task is added.

**Comment by thisisfaaris** [comment]
Develop a component for displaying the list of tasks. Each task should include text, an edit option, and a delete option. Completed tasks should be visually distinguished with a strikethrough. Use mapping and repetition to display tasks fetched from the backend. Allow users to edit or delete tasks directly from this component.
